ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_document_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_verification_status VARCHAR(50) DEFAULT 'UNVERIFIED';
